apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: data-platform
resources:
  - namespace.yaml
  - ../../base
patchesStrategicMerge:
  - airflow-patch.yaml
  - superset-patch.yaml