apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tenant-operator
  namespace: tenant-system
spec:
  interval: 5m
  chart:
    spec:
      chart: tenant-operator
      version: "1.0.0"
      sourceRef:
        kind: HelmRepository
        name: tenant-operator
        namespace: flux-system
  values:
    rbac:
      create: true
    
    controller:
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 128Mi
          
    # Configuration for tenant segregation
    tenantConfig:
      namespaceIsolation: true
      networkPolicies: true
      resourceQuotas: true
      defaultLimits:
        cpu: "4"
        memory: "8Gi"
      defaultRequests:
        cpu: "100m"
        memory: "128Mi"