apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: finance-domain
resources:
  - namespace.yaml
  - ../../base
  - dbt-jobs.yaml
  - airflow-dags.yaml
  - superset-dashboards.yaml
secretGenerator:
  - name: finance-secrets
    files:
      - secrets/database.env
    type: Opaque