apiVersion: v1
kind: ConfigMap
metadata:
  name: finance-domain-config
  namespace: finance-domain
data:
  domain.yaml: |
    name: finance
    description: Finance data domain
    owner: finance-team
    contacts:
      - name: Finance Data Team
        email: finance-data@example.com
    databases:
      - name: finance_dw
        type: data_warehouse
      - name: finance_raw
        type: landing_zone